### ISSUE TITLE
svelteBracketNewLine: false not working

### ISSUE THREAD

**Issue by janosh** [sveltejs/prettier-plugin-svelte#183]
After the update to v2, I added `svelteBracketNewLine: false` to my Prettier config as I prefer the previous formatting. This setting seems to be ignored though. Prettier now closes multiline tags on a new line regardless. Here's my full config:

```yml
# .prettierrc.yml
semi: false
singleQuote: true
svelteBracketNewLine: false
overrides:
  - files: '*.svelte'
    options:
      printWidth: 90
```

![diff](https://user-images.githubusercontent.com/30958850/103872128-440b2c00-50ce-11eb-8740-c01192d8b754.png)
